spring:
  cloud:
    vault:
      port: 8200
      token: 00000000-0000-0000-0000-000000000000
      host: 127.0.0.1
      scheme: http
      kv:
        enabled: true
        profile-separator: /
        application-name: test-app
        backend: secret
        profiles: prod
        backend-version: 2